DROP DATABASE IF EXISTS "EVI";
DROP SCHEMA IF EXISTS evi;
DROP ROLE IF EXISTS evi;
CREATE DATABASE "EVI" ENCODING 'utf-8';
\c "EVI"
CREATE ROLE evi ENCRYPTED PASSWORD 'md542ff386045b8d631575d87d623a557c7' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
CREATE SCHEMA evi AUTHORIZATION evi;
