DROP DATABASE IF EXISTS "KEMOD";
DROP SCHEMA IF EXISTS kemod;
DROP ROLE IF EXISTS kemod;
CREATE DATABASE "KEMOD" ENCODING 'utf-8';
\c "KEMOD"
CREATE ROLE kemod ENCRYPTED PASSWORD 'md5d41d8cd98f00b204e9800998ecf8427e' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
CREATE SCHEMA kemod AUTHORIZATION kemod;
